linters:
  disable-all: true
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - dupl
    - funlen
    - gci
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - importas
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - staticcheck
    - stylecheck
    - unparam
    - whitespace

run:
  timeout: 10m

issues:
  exclude-dirs:
    - ^client/            # generated code
    - ^pkg/api/           # generated code
    - ^pkg/csiclientmocks # generated code
    - ^pkg/k8sclientmocks # generated code
  exclude-files:
    - ^release-tools/filter-junit.go
  exclude-rules:
    - path: _test\.go$
      linters:
        - dupl
        - funlen
        - gci
        - gocognit
        - gocritic
        - gocyclo
        - lll
        - nestif
        - unparam

linters-settings:
  funlen:
    lines: 240
    statements: 160
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kubernetes-csi/external-snapshot-metadata)
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  importas:
    no-unaliased: true
    alias:
      - pkg: github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1
        alias: snapshotv1
      - pkg: github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/fake
        alias: fakesnapshot
      - pkg: github.com/kubernetes-csi/external-snapshotter/v8/pkg/utils
        alias: snapshotutils
      - pkg: google.golang.org/grpc/health/grpc_health_v1
        alias: healthpb
      - pkg: k8s.io/api/authentication/v1
        alias: authv1
      - pkg: k8s.io/api/authorization/v1
        alias: authzv1
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: apimetav1
      - pkg: k8s.io/apimachinery/pkg/runtime
        alias: apiruntime
      - pkg: k8s.io/client-go/testing
        alias: clientgotesting
  lll:
    line-length: 240
  nakedret:
    max-func-lines: 2
  nestif:
    min-complexity: 6
  staticcheck:
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016" ]
  stylecheck:
    checks: [ "all", "-ST1001", "-ST1005", "-ST1016", "-ST1023", "-ST1000"]
