linters:
  disable-all: true
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - dupl
    - funlen
    - gci
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - importas
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - staticcheck
    - stylecheck
    - unparam
    - whitespace

run:
  timeout: 10m

issues:
  exclude-dirs:
    - ^client/    # generated code
    - ^pkg/api/   # generated code
  exclude-files:
    - ^release-tools/filter-junit.go
  exclude-rules:
    - path: _test\.go$
      linters:
        - dupl
        - funlen
        - gci
        - gocognit
        - gocritic
        - gocyclo
        - lll
        - nestif
        - unparam

linters-settings:
  funlen:
    lines: 240
    statements: 160
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  lll:
    line-length: 240
  nakedret:
    max-func-lines: 2
  nestif:
    min-complexity: 6
  staticcheck:
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016" ]
  stylecheck:
    checks: [ "all", "-ST1001", "-ST1005", "-ST1016", "-ST1023", "-ST1000"]
