apiVersion: v1
kind: Service
metadata:
  name: csi-dummyplugin
  namespace: csi-driver
  labels:
    app.kubernetes.io/name: csi-dummyplugin
spec:
  ports:
  - name: cbt
    port: 6443
    protocol: TCP
    targetPort: 50051
  selector:
    app.kubernetes.io/name: csi-dummyplugin
